// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_4YSxjlt-pvJ6v0jDIt_ndj-gTG3DJQ',
    appId: '1:1039212342844:web:2c6b9d1d51565f4df09d39',
    messagingSenderId: '1039212342844',
    projectId: 'surveyapp-7915b',
    authDomain: 'surveyapp-7915b.firebaseapp.com',
    storageBucket: 'surveyapp-7915b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY9LoQqBn7vUJHrHY7e1rgTl1OfEtTFCA',
    appId: '1:1039212342844:android:3c0087d98680e410f09d39',
    messagingSenderId: '1039212342844',
    projectId: 'surveyapp-7915b',
    storageBucket: 'surveyapp-7915b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo7Nq5F5TkJmmoJR6wunGdBcMUKpie75I',
    appId: '1:1039212342844:ios:d7b86742ddb65c16f09d39',
    messagingSenderId: '1039212342844',
    projectId: 'surveyapp-7915b',
    storageBucket: 'surveyapp-7915b.appspot.com',
    iosBundleId: 'com.example.flutterSurveyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo7Nq5F5TkJmmoJR6wunGdBcMUKpie75I',
    appId: '1:1039212342844:ios:82f5203eded1d594f09d39',
    messagingSenderId: '1039212342844',
    projectId: 'surveyapp-7915b',
    storageBucket: 'surveyapp-7915b.appspot.com',
    iosBundleId: 'com.example.flutterSurveyDashboard.RunnerTests',
  );
}
